Repository codesquad-member-2020/airbnb-10, pull requests merged in 2020-06, with the labels that each got.

#41 Feature/fe modal event
  FE/airbnb/src/components/header/ModalButtons.jsx
  FE/airbnb/src/components/header/date/CalendarButtons.jsx
  FE/airbnb/src/components/header/date/Date.jsx
  FE/airbnb/src/components/header/personnel/Personnel.jsx
  FE/airbnb/src/components/header/price/Price.jsx
  FE/airbnb/src/components/header/price/PriceBoxes.jsx
  FE/airbnb/src/components/header/price/PriceModal.jsx
  FE/airbnb/src/components/header/price/PriceRange.jsx
  FE/airbnb/src/components/header/price/chart/Chart.jsx
  FE/airbnb/src/components/header/price/chart/ChartBar.jsx
  FE/airbnb/src/components/header/price/chart/ChartConstants.js
  FE/airbnb/src/style/CustomStyle.jsx
Labels: FE

#50 Feature/fe-pagination
  FE/airbnb/package.json
  FE/airbnb/src/App.js
  FE/airbnb/src/components/header/ModalButtons.jsx
  FE/airbnb/src/components/header/price/chart/Chart.jsx
  FE/airbnb/src/hooks/useFetch.jsx
  FE/airbnb/yarn.lock
Labels: FE

#54 Feature/fe pagination
  FE/airbnb/.env.development
  FE/airbnb/src/components/header/ModalButtons.jsx
  FE/airbnb/src/components/header/personnel/Personnel.jsx
  FE/airbnb/src/components/header/personnel/PersonnelTabColumn.jsx
  FE/airbnb/src/components/header/price/PriceModal.jsx
  FE/airbnb/src/components/header/price/chart/Chart.jsx
  FE/airbnb/src/components/rooms/Rooms.jsx
  FE/airbnb/src/hooks/useFetch.jsx
  FE/airbnb/src/hooks/useUpdateStore.jsx
  FE/airbnb/src/modules/personnel.js
  FE/airbnb/src/modules/roomsList.js
  FE/airbnb/src/util/util.js
Labels: FE

#61 Feature/fe pagination
  FE/airbnb/src/components/nav/Nav.jsx
  FE/airbnb/src/components/pagination/Pagination.jsx
  FE/airbnb/src/components/reservation/Reservation.jsx
  FE/airbnb/src/hooks/useUpdateStore.jsx
  FE/airbnb/src/modules/roomsList.js
  FE/airbnb/src/util/util.js
Labels: FE

#62 Feature/fe pagination
  FE/airbnb/src/components/pagination/Pagination.jsx
  FE/airbnb/src/components/reservation/Reservation.jsx
  FE/airbnb/src/components/rooms/Rooms.jsx
  FE/airbnb/src/hooks/useFetch.jsx
  FE/airbnb/src/modules/pagination.js
  FE/airbnb/src/modules/roomsList.js
Labels: FE

#66 [#28] fix: 필터링 버그 해결
  BE/src/main/resources/mapper/mapper.xml
Labels: BE, bug

#68 Feature/fe pagination
  FE/airbnb/package-lock.json
  FE/airbnb/package.json
  FE/airbnb/public/index.html
  FE/airbnb/src/components/header/ModalButtons.jsx
  FE/airbnb/src/components/header/date/Date.jsx
  FE/airbnb/src/components/header/personnel/Personnel.jsx
  FE/airbnb/src/components/header/price/Price.jsx
  FE/airbnb/src/components/header/price/PriceModal.jsx
  FE/airbnb/src/components/reservation/Reservation.jsx
  FE/airbnb/src/components/rooms/RoomsList.jsx
  FE/airbnb/src/util/util.js
  FE/airbnb/yarn.lock
Labels: FE

#73 [#55] DAO 클래스와 xml 연동하기
  BE/src/main/java/com/codesquad/airbnb/business/BookService.java
  BE/src/main/java/com/codesquad/airbnb/business/FilterService.java
  BE/src/main/java/com/codesquad/airbnb/dao/AccommodationDAO.java
  BE/src/main/java/com/codesquad/airbnb/dao/AccommodationMapper.java
  BE/src/main/resources/mapper/mapper.xml
  BE/src/test/java/com/codesquad/airbnb/dao/AccommodationMapperTest.java
  BE/src/test/java/com/codesquad/airbnb/dao/BookingMapperTest.java
Labels: BE
